FileVersion = 1
Dependencies = {corlib = "*", Bulkan = "*", ImGui = "*"}

[Project]
Name = "ImGuiImplVulkan"
TargetType = "BeefLib"
StartupObject = "imgui_vulkan_beef.Program"
DefaultNamespace = "ImGui"
